"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HideoutAreas = void 0;
var HideoutAreas;
(function (HideoutAreas) {
    HideoutAreas[HideoutAreas["NOTSET"] = -1] = "NOTSET";
    HideoutAreas[HideoutAreas["VENTS"] = 0] = "VENTS";
    HideoutAreas[HideoutAreas["SECURITY"] = 1] = "SECURITY";
    HideoutAreas[HideoutAreas["LAVATORY"] = 2] = "LAVATORY";
    HideoutAreas[HideoutAreas["STASH"] = 3] = "STASH";
    HideoutAreas[HideoutAreas["GENERATOR"] = 4] = "GENERATOR";
    HideoutAreas[HideoutAreas["HEATING"] = 5] = "HEATING";
    HideoutAreas[HideoutAreas["WATER_COLLECTOR"] = 6] = "WATER_COLLECTOR";
    HideoutAreas[HideoutAreas["MEDSTATION"] = 7] = "MEDSTATION";
    HideoutAreas[HideoutAreas["NUTRITION_UNIT"] = 8] = "NUTRITION_UNIT";
    HideoutAreas[HideoutAreas["REST_SPACE"] = 9] = "REST_SPACE";
    HideoutAreas[HideoutAreas["WORKBENCH"] = 10] = "WORKBENCH";
    HideoutAreas[HideoutAreas["INTEL_CENTER"] = 11] = "INTEL_CENTER";
    HideoutAreas[HideoutAreas["SHOOTING_RANGE"] = 12] = "SHOOTING_RANGE";
    HideoutAreas[HideoutAreas["LIBRARY"] = 13] = "LIBRARY";
    HideoutAreas[HideoutAreas["SCAV_CASE"] = 14] = "SCAV_CASE";
    HideoutAreas[HideoutAreas["ILLUMINATION"] = 15] = "ILLUMINATION";
    HideoutAreas[HideoutAreas["PLACE_OF_FAME"] = 16] = "PLACE_OF_FAME";
    HideoutAreas[HideoutAreas["AIR_FILTERING"] = 17] = "AIR_FILTERING";
    HideoutAreas[HideoutAreas["SOLAR_POWER"] = 18] = "SOLAR_POWER";
    HideoutAreas[HideoutAreas["BOOZE_GENERATOR"] = 19] = "BOOZE_GENERATOR";
    HideoutAreas[HideoutAreas["BITCOIN_FARM"] = 20] = "BITCOIN_FARM";
    HideoutAreas[HideoutAreas["CHRISTMAS_TREE"] = 21] = "CHRISTMAS_TREE";
    HideoutAreas[HideoutAreas["EMERGENCY_WALL"] = 22] = "EMERGENCY_WALL";
    HideoutAreas[HideoutAreas["GYM"] = 23] = "GYM";
    HideoutAreas[HideoutAreas["WEAPON_STAND"] = 24] = "WEAPON_STAND";
    HideoutAreas[HideoutAreas["WEAPON_STAND_SECONDARY"] = 25] = "WEAPON_STAND_SECONDARY";
})(HideoutAreas || (exports.HideoutAreas = HideoutAreas = {}));
