"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SkillTypes = void 0;
var SkillTypes;
(function (SkillTypes) {
    SkillTypes["BOT_RELOAD"] = "BotReload";
    SkillTypes["BOT_SOUND"] = "BotSound";
    SkillTypes["HIDEOUT_MANAGEMENT"] = "HideoutManagement";
    SkillTypes["CRAFTING"] = "Crafting";
    SkillTypes["METABOLISM"] = "Metabolism";
    SkillTypes["IMMUNITY"] = "Immunity";
    SkillTypes["ENDURANCE"] = "Endurance";
    SkillTypes["STRENGTH"] = "Strength";
    SkillTypes["VITALITY"] = "Vitality";
    SkillTypes["HEALTH"] = "Health";
    SkillTypes["STRESS_RESISTANCE"] = "StressResistance";
    SkillTypes["THROWING"] = "Throwing";
    SkillTypes["RECOIL_CONTROL"] = "RecoilControl";
    SkillTypes["COVERT_MOVEMENT"] = "CovertMovement";
    SkillTypes["FIELD_MEDICINE"] = "FieldMedicine";
    SkillTypes["SEARCH"] = "Search";
    SkillTypes["SNIPING"] = "Sniping";
    SkillTypes["PERCEPTION"] = "Perception";
    SkillTypes["INTELLECT"] = "Intellect";
    SkillTypes["ATTENTION"] = "Attention";
    SkillTypes["CHARISMA"] = "Charisma";
    SkillTypes["MEMORY"] = "Memory";
    SkillTypes["MELEE"] = "Melee";
    SkillTypes["SURGERY"] = "Surgery";
    SkillTypes["AIM_DRILLS"] = "AimDrills";
    SkillTypes["TROUBLESHOOTING"] = "TroubleShooting";
    SkillTypes["PRONE_MOVEMENT"] = "ProneMovement";
    SkillTypes["FIRST_AID"] = "FirstAid";
    SkillTypes["LIGHT_VESTS"] = "LightVests";
    SkillTypes["HEAVY_VESTS"] = "HeavyVests";
    SkillTypes["WEAPON_MODDING"] = "WeaponModding";
    SkillTypes["ADVANCED_MODDING"] = "AdvancedModding";
    SkillTypes["NIGHT_OPS"] = "NightOps";
    SkillTypes["SILENT_OPS"] = "SilentOps";
    SkillTypes["LOCKPICKING"] = "Lockpicking";
    /** Also called Weapon Maintenance*/
    SkillTypes["WEAPON_TREATMENT"] = "WeaponTreatment";
    SkillTypes["MAG_DRILLS"] = "MagDrills";
    SkillTypes["FREE_TRADING"] = "Freetrading";
    SkillTypes["AUCTIONS"] = "Auctions";
    SkillTypes["CLEAN_OPS"] = "Cleanoperations";
    SkillTypes["BARTER"] = "Barter";
    SkillTypes["SHADOW_CONNECTIONS"] = "Shadowconnections";
    SkillTypes["TASK_PERFORMANCE"] = "Taskperformance";
    SkillTypes["BEAR_ASSAULT_OPS"] = "BearAssaultoperations";
    SkillTypes["BEAR_AUTHORITY"] = "BearAuthority";
    SkillTypes["BEAR_AK_SYSTEMS"] = "BearAksystems";
    SkillTypes["BEAR_HEAVY_CAL"] = "BearHeavycaliber";
    SkillTypes["BEAR_RAW_POWER"] = "BearRawpower";
    SkillTypes["USEC_AR_SYSTEMS"] = "UsecArsystems";
    SkillTypes["USEC_DEEP_WEAPON_MOD"] = "UsecDeepweaponmodding_Settings";
    SkillTypes["USEC_LONG_RANGE_OPTICS"] = "UsecLongrangeoptics_Settings";
    SkillTypes["USEC_NEGOTIATIONS"] = "UsecNegotiations";
    SkillTypes["USEC_TACTICS"] = "UsecTactics";
})(SkillTypes || (exports.SkillTypes = SkillTypes = {}));
