"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WildSpawnTypeNumber = void 0;
var WildSpawnTypeNumber;
(function (WildSpawnTypeNumber) {
    WildSpawnTypeNumber[WildSpawnTypeNumber["MARKSMAN"] = 0] = "MARKSMAN";
    WildSpawnTypeNumber[WildSpawnTypeNumber["ASSAULT"] = 1] = "ASSAULT";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSTEST"] = 2] = "BOSSTEST";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSBULLY"] = 3] = "BOSSBULLY";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERTEST"] = 4] = "FOLLOWERTEST";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERBULLY"] = 5] = "FOLLOWERBULLY";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSKILLA"] = 6] = "BOSSKILLA";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSKOJANIY"] = 7] = "BOSSKOJANIY";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERKOJANIY"] = 8] = "FOLLOWERKOJANIY";
    WildSpawnTypeNumber[WildSpawnTypeNumber["PMCBOT"] = 9] = "PMCBOT";
    WildSpawnTypeNumber[WildSpawnTypeNumber["CURSEDASSAULT"] = 10] = "CURSEDASSAULT";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSGLUHAR"] = 11] = "BOSSGLUHAR";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERGLUHARASSAULT"] = 12] = "FOLLOWERGLUHARASSAULT";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERGLUHARSECURITY"] = 13] = "FOLLOWERGLUHARSECURITY";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERGLUHARSCOUT"] = 14] = "FOLLOWERGLUHARSCOUT";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERGLUHARSNIPE"] = 15] = "FOLLOWERGLUHARSNIPE";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERSANITAR"] = 16] = "FOLLOWERSANITAR";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSSANITAR"] = 17] = "BOSSSANITAR";
    WildSpawnTypeNumber[WildSpawnTypeNumber["TEST"] = 18] = "TEST";
    WildSpawnTypeNumber[WildSpawnTypeNumber["ASSAULTGROUP"] = 19] = "ASSAULTGROUP";
    WildSpawnTypeNumber[WildSpawnTypeNumber["SECTANTWARRIOR"] = 20] = "SECTANTWARRIOR";
    WildSpawnTypeNumber[WildSpawnTypeNumber["SECTANTPRIEST"] = 21] = "SECTANTPRIEST";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSTAGILLA"] = 22] = "BOSSTAGILLA";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERTAGILLA"] = 23] = "FOLLOWERTAGILLA";
    WildSpawnTypeNumber[WildSpawnTypeNumber["EXUSEC"] = 24] = "EXUSEC";
    WildSpawnTypeNumber[WildSpawnTypeNumber["GIFTER"] = 25] = "GIFTER";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSKNIGHT"] = 26] = "BOSSKNIGHT";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERBIGPIPE"] = 27] = "FOLLOWERBIGPIPE";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERBIRDEYE"] = 28] = "FOLLOWERBIRDEYE";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSZRYACHIY"] = 29] = "BOSSZRYACHIY";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERZRYACHIY"] = 30] = "FOLLOWERZRYACHIY";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSBOAR"] = 32] = "BOSSBOAR";
    WildSpawnTypeNumber[WildSpawnTypeNumber["FOLLOWERBOAR"] = 33] = "FOLLOWERBOAR";
    WildSpawnTypeNumber[WildSpawnTypeNumber["ARENAFIGHTER"] = 34] = "ARENAFIGHTER";
    WildSpawnTypeNumber[WildSpawnTypeNumber["ARENAFIGHTEREVENT"] = 35] = "ARENAFIGHTEREVENT";
    WildSpawnTypeNumber[WildSpawnTypeNumber["BOSSBOARSNIPER"] = 36] = "BOSSBOARSNIPER";
    WildSpawnTypeNumber[WildSpawnTypeNumber["CRAZYASSAULTEVENT"] = 37] = "CRAZYASSAULTEVENT";
    WildSpawnTypeNumber[WildSpawnTypeNumber["SPTUSEC"] = 38] = "SPTUSEC";
    WildSpawnTypeNumber[WildSpawnTypeNumber["SPTBEAR"] = 39] = "SPTBEAR";
})(WildSpawnTypeNumber || (exports.WildSpawnTypeNumber = WildSpawnTypeNumber = {}));
